//! In-silico protein digestion.
//!
//! Simulates enzymatic cleavage of protein sequences into peptides.
//! Supports all enzyme types defined in [`protein_copilot_core::search_params::Enzyme`].

use protein_copilot_core::search_params::Enzyme;

// Re-export for external callers
pub use crate::chemistry::{is_standard_sequence, peptide_mass, peptide_mz, residue_mass};

/// A peptide generated by in-silico digestion.
#[derive(Debug, Clone)]
pub struct DigestedPeptide {
    /// Amino acid sequence.
    pub sequence: String,
    /// Protein accession this peptide came from.
    pub protein_accession: String,
    /// Monoisotopic neutral mass (Da).
    pub neutral_mass: f64,
    /// Whether this peptide starts at the protein N-terminus.
    pub is_protein_nterm: bool,
    /// Whether this peptide ends at the protein C-terminus.
    pub is_protein_cterm: bool,
}

/// Digests a protein sequence with the given enzyme and missed cleavages.
///
/// Uses default peptide length range (6–50). For configurable lengths,
/// use [`digest_with_length`].
pub fn digest(
    sequence: &str,
    protein_accession: &str,
    enzyme: &Enzyme,
    missed_cleavages: u32,
) -> Vec<DigestedPeptide> {
    let _span = tracing::info_span!("digest",
        protein = %protein_accession,
        enzyme = ?enzyme,
        missed_cleavages = missed_cleavages,
    ).entered();
    let result = digest_with_length(sequence, protein_accession, enzyme, missed_cleavages, 6, 50);
    tracing::info!(peptides = result.len(), "digestion complete");
    result
}

/// Digests a protein sequence with configurable peptide length range.
///
/// `min_length` and `max_length` control accepted peptide lengths (in residues).
/// Also tracks whether each peptide is at the protein N- or C-terminus.
pub fn digest_with_length(
    sequence: &str,
    protein_accession: &str,
    enzyme: &Enzyme,
    missed_cleavages: u32,
    min_length: u32,
    max_length: u32,
) -> Vec<DigestedPeptide> {
    let cleavage_sites = find_cleavage_sites(sequence, enzyme);
    let fragments = split_at_sites(sequence, &cleavage_sites);
    let num_fragments = fragments.len();

    let mut peptides = Vec::new();

    // Generate peptides with 0..=missed_cleavages missed sites
    for mc in 0..=(missed_cleavages as usize) {
        for (i, window) in fragments.windows(mc + 1).enumerate() {
            let combined: String = window.concat();
            let len = combined.len() as u32;
            if len >= min_length && len <= max_length {
                // Skip peptides containing non-standard amino acids
                if let Some(mass) = peptide_mass(&combined) {
                    let is_nterm = i == 0;
                    let is_cterm = i + mc + 1 == num_fragments;
                    peptides.push(DigestedPeptide {
                        sequence: combined,
                        protein_accession: protein_accession.to_string(),
                        neutral_mass: mass,
                        is_protein_nterm: is_nterm,
                        is_protein_cterm: is_cterm,
                    });
                }
            }
        }
    }

    peptides
}

/// Finds cleavage positions in the sequence based on enzyme rules.
///
/// Returns a sorted list of positions where cleavage occurs.
/// A position `i` means the enzyme cuts between `sequence[i-1]` and `sequence[i]`.
fn find_cleavage_sites(sequence: &str, enzyme: &Enzyme) -> Vec<usize> {
    let chars: Vec<char> = sequence.chars().collect();
    let len = chars.len();
    let mut sites = Vec::new();

    if len < 2 {
        return sites;
    }

    match enzyme {
        Enzyme::Trypsin => {
            for (i, pair) in chars.windows(2).enumerate() {
                if (pair[0] == 'K' || pair[0] == 'R') && pair[1] != 'P' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::TrypsinP => {
            for (i, pair) in chars.windows(2).enumerate() {
                if pair[0] == 'K' || pair[0] == 'R' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::LysC => {
            for (i, pair) in chars.windows(2).enumerate() {
                if pair[0] == 'K' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::GluC => {
            for (i, pair) in chars.windows(2).enumerate() {
                if pair[0] == 'D' || pair[0] == 'E' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::AspN => {
            for (i, &ch) in chars.iter().enumerate().skip(1) {
                if ch == 'D' {
                    sites.push(i);
                }
            }
        }
        Enzyme::Chymotrypsin => {
            for (i, pair) in chars.windows(2).enumerate() {
                if matches!(pair[0], 'F' | 'W' | 'Y' | 'L') {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::NonSpecific => {
            for i in 1..len {
                sites.push(i);
            }
        }
        Enzyme::Custom { .. } => {
            // Fall back to no cleavage (whole protein as one peptide)
        }
    }

    sites
}

/// Splits a sequence at the given cleavage sites into fragments.
fn split_at_sites(sequence: &str, sites: &[usize]) -> Vec<String> {
    let mut fragments = Vec::new();
    let mut prev = 0;

    for &site in sites {
        if site > prev && site <= sequence.len() {
            fragments.push(sequence[prev..site].to_string());
            prev = site;
        }
    }

    // Last fragment
    if prev < sequence.len() {
        fragments.push(sequence[prev..].to_string());
    }

    fragments
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trypsin_basic_digestion() {
        // PEPTIDEK|ANSTHERPEPTIDER|LASTPART
        // Trypsin cuts after K and R (not before P)
        let peptides = digest(
            "PEPTIDEKANSTHERPEPTIDERLASTPART",
            "P001",
            &Enzyme::Trypsin,
            0,
        );
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        assert!(seqs.contains(&"PEPTIDEK"));
        assert!(seqs.contains(&"ANSTHERPEPTIDER"));
    }

    #[test]
    fn trypsin_does_not_cut_before_p() {
        // KP should NOT be a cleavage site for Trypsin
        let peptides = digest("AVCDEFKPGHIKLMNR", "P001", &Enzyme::Trypsin, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // "AVCDEFKPGHIK" should be one peptide (K followed by P → no cut)
        assert!(seqs.contains(&"AVCDEFKPGHIK"));
    }

    #[test]
    fn trypsinp_cuts_before_p() {
        // TrypsinP cuts after K/R even before P
        // Sequence: AVCDEFK | PSTGHIKLMNQR (TrypsinP cuts at K pos7, then K pos14, R pos18)
        let peptides = digest("AVCDEFKPSTGHIKLMNQR", "P001", &Enzyme::TrypsinP, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        assert!(
            seqs.contains(&"AVCDEFK"),
            "expected AVCDEFK, got: {:?}",
            seqs
        );
        assert!(
            seqs.contains(&"PSTGHIK"),
            "expected PSTGHIK, got: {:?}",
            seqs
        );
    }

    #[test]
    fn lysc_cuts_after_k_only() {
        let peptides = digest("PEPTIDEKANATHERRPART", "P001", &Enzyme::LysC, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        assert!(seqs.contains(&"PEPTIDEK"));
        // R should not be a cleavage site for LysC
        assert!(seqs.contains(&"ANATHERRPART"));
    }

    #[test]
    fn gluc_cuts_after_de() {
        let peptides = digest("AVCSQEDFGHIKLMNE", "P001", &Enzyme::GluC, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // Should cut after D and E
        assert!(seqs.iter().any(|s| s.ends_with('D') || s.ends_with('E')));
    }

    #[test]
    fn aspn_cuts_before_d() {
        let peptides = digest("AVCSEFGDKLMNPQRST", "P001", &Enzyme::AspN, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // Should cut BEFORE D → "AVCSEFG" and "DKLMNPQRST"
        assert!(seqs.contains(&"AVCSEFG"));
        assert!(seqs.contains(&"DKLMNPQRST"));
    }

    #[test]
    fn chymotrypsin_cuts_after_fwyl() {
        let peptides = digest("AVCDEFGHIKLMNPQRSTW", "P001", &Enzyme::Chymotrypsin, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // Should cut after F
        assert!(seqs.iter().any(|s| s.ends_with('F')));
    }

    #[test]
    fn missed_cleavages_produce_longer_peptides() {
        let mc0 = digest("PEPTIDEKANSTHERRLASTR", "P001", &Enzyme::Trypsin, 0);
        let mc1 = digest("PEPTIDEKANSTHERRLASTR", "P001", &Enzyme::Trypsin, 1);
        // With missed cleavages, should have more peptides (including merged ones)
        assert!(mc1.len() >= mc0.len());
    }

    #[test]
    fn peptide_mass_calculation() {
        let mass = peptide_mass("GGGGGG").expect("standard residues");
        let expected = 57.021464 * 6.0 + crate::chemistry::WATER_MASS;
        assert!((mass - expected).abs() < 0.001);
    }

    #[test]
    fn peptide_mz_calculation() {
        let mass = 1000.0;
        let mz_z2 = peptide_mz(mass, 2);
        // (1000 + 2*1.007276) / 2 = 501.007276
        assert!((mz_z2 - 501.007276).abs() < 0.001);
    }

    #[test]
    fn peptide_length_filter() {
        // Very short peptides (< 6 aa) should be filtered out (default digest)
        let peptides = digest("AVKCDKEFGHIKLMNR", "P001", &Enzyme::Trypsin, 0);
        for p in &peptides {
            assert!(p.sequence.len() >= 6, "peptide too short: {}", p.sequence);
        }
    }

    #[test]
    fn digest_with_length_respects_min() {
        let peptides = digest_with_length(
            "PEPTIDEKANSTHERPEPTIDERLASTPART",
            "P001",
            &Enzyme::Trypsin,
            0,
            8,
            50,
        );
        for p in &peptides {
            assert!(p.sequence.len() >= 8, "too short: {}", p.sequence);
        }
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        assert!(seqs.contains(&"PEPTIDEK")); // exactly 8
    }

    #[test]
    fn digest_with_length_respects_max() {
        let peptides = digest_with_length(
            "PEPTIDEKANSTHERPEPTIDERLASTPART",
            "P001",
            &Enzyme::Trypsin,
            0,
            6,
            10,
        );
        for p in &peptides {
            assert!(p.sequence.len() <= 10, "too long: {}", p.sequence);
        }
    }

    #[test]
    fn digest_marks_protein_nterm() {
        // PEPTIDEK | ANSTHER | TENDSWTGFAM
        // 3 fragments, all >= 6 chars, last has no K/R → stays as C-terminal
        let peptides = digest_with_length(
            "PEPTIDEKANSTHERTENDSWTGFAM",
            "P001",
            &Enzyme::Trypsin,
            0,
            6,
            50,
        );
        assert_eq!(peptides.len(), 3);
        // First peptide should be protein N-terminal
        assert!(
            peptides[0].is_protein_nterm,
            "first peptide should be N-term"
        );
        assert!(!peptides[0].is_protein_cterm);
        // Last peptide should be protein C-terminal
        let last = peptides.last().unwrap();
        assert!(last.is_protein_cterm, "last peptide should be C-term");
        assert!(!last.is_protein_nterm);
        // Internal peptide is neither
        assert!(!peptides[1].is_protein_nterm);
        assert!(!peptides[1].is_protein_cterm);
    }

    #[test]
    fn digest_single_peptide_is_both_terminal() {
        let peptides = digest_with_length("PEPTIDEK", "P001", &Enzyme::Trypsin, 0, 6, 50);
        assert_eq!(peptides.len(), 1);
        assert!(peptides[0].is_protein_nterm);
        assert!(peptides[0].is_protein_cterm);
    }
}
