//! In-silico protein digestion.
//!
//! Simulates enzymatic cleavage of protein sequences into peptides.
//! Supports all enzyme types defined in [`protein_copilot_core::search_params::Enzyme`].
//!
//! # Amino acid monoisotopic masses
//!
//! Standard residue masses used for theoretical peptide mass calculation.

use protein_copilot_core::search_params::Enzyme;

/// A peptide generated by in-silico digestion.
#[derive(Debug, Clone)]
pub struct DigestedPeptide {
    /// Amino acid sequence.
    pub sequence: String,
    /// Protein accession this peptide came from.
    pub protein_accession: String,
    /// Monoisotopic neutral mass (Da).
    pub neutral_mass: f64,
}

/// Monoisotopic residue masses (Da).
fn residue_mass(aa: char) -> f64 {
    match aa {
        'G' => 57.021464,
        'A' => 71.037114,
        'V' => 99.068414,
        'L' => 113.084064,
        'I' => 113.084064,
        'P' => 97.052764,
        'F' => 147.068414,
        'W' => 186.079313,
        'M' => 131.040485,
        'S' => 87.032028,
        'T' => 101.047679,
        'C' => 103.009185,
        'Y' => 163.063329,
        'H' => 137.058912,
        'D' => 115.026943,
        'E' => 129.042593,
        'N' => 114.042927,
        'Q' => 128.058578,
        'K' => 128.094963,
        'R' => 156.101111,
        _ => 0.0, // unknown residue, skip
    }
}

/// Water mass added for intact peptide (N-term H + C-term OH).
const WATER_MASS: f64 = 18.010565;

/// Calculates the monoisotopic neutral mass of a peptide sequence.
pub fn peptide_mass(sequence: &str) -> f64 {
    let sum: f64 = sequence.chars().map(residue_mass).sum();
    sum + WATER_MASS
}

/// Calculates the m/z value for a peptide at a given charge state.
///
/// Formula: m/z = (neutral_mass + charge × proton_mass) / charge
pub fn peptide_mz(neutral_mass: f64, charge: i32) -> f64 {
    const PROTON_MASS: f64 = 1.007276;
    (neutral_mass + charge as f64 * PROTON_MASS) / charge as f64
}

/// Digests a protein sequence with the given enzyme and missed cleavages.
///
/// Returns a list of peptide sequences. Supports all enzyme types from core.
pub fn digest(
    sequence: &str,
    protein_accession: &str,
    enzyme: &Enzyme,
    missed_cleavages: u32,
) -> Vec<DigestedPeptide> {
    let cleavage_sites = find_cleavage_sites(sequence, enzyme);
    let fragments = split_at_sites(sequence, &cleavage_sites);

    let mut peptides = Vec::new();

    // Generate peptides with 0..=missed_cleavages missed sites
    for mc in 0..=(missed_cleavages as usize) {
        for window in fragments.windows(mc + 1) {
            let combined: String = window.concat();
            if combined.len() >= 6 && combined.len() <= 50 {
                // Filter by reasonable peptide length
                let mass = peptide_mass(&combined);
                peptides.push(DigestedPeptide {
                    sequence: combined,
                    protein_accession: protein_accession.to_string(),
                    neutral_mass: mass,
                });
            }
        }
    }

    peptides
}

/// Finds cleavage positions in the sequence based on enzyme rules.
///
/// Returns a sorted list of positions where cleavage occurs.
/// A position `i` means the enzyme cuts between `sequence[i-1]` and `sequence[i]`.
fn find_cleavage_sites(sequence: &str, enzyme: &Enzyme) -> Vec<usize> {
    let chars: Vec<char> = sequence.chars().collect();
    let len = chars.len();
    let mut sites = Vec::new();

    if len < 2 {
        return sites;
    }

    match enzyme {
        Enzyme::Trypsin => {
            for (i, pair) in chars.windows(2).enumerate() {
                if (pair[0] == 'K' || pair[0] == 'R') && pair[1] != 'P' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::TrypsinP => {
            for (i, pair) in chars.windows(2).enumerate() {
                if pair[0] == 'K' || pair[0] == 'R' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::LysC => {
            for (i, pair) in chars.windows(2).enumerate() {
                if pair[0] == 'K' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::GluC => {
            for (i, pair) in chars.windows(2).enumerate() {
                if pair[0] == 'D' || pair[0] == 'E' {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::AspN => {
            for (i, &ch) in chars.iter().enumerate().skip(1) {
                if ch == 'D' {
                    sites.push(i);
                }
            }
        }
        Enzyme::Chymotrypsin => {
            for (i, pair) in chars.windows(2).enumerate() {
                if matches!(pair[0], 'F' | 'W' | 'Y' | 'L') {
                    sites.push(i + 1);
                }
            }
        }
        Enzyme::NonSpecific => {
            for i in 1..len {
                sites.push(i);
            }
        }
        Enzyme::Custom { .. } => {
            // Fall back to no cleavage (whole protein as one peptide)
        }
    }

    sites
}

/// Splits a sequence at the given cleavage sites into fragments.
fn split_at_sites(sequence: &str, sites: &[usize]) -> Vec<String> {
    let mut fragments = Vec::new();
    let mut prev = 0;

    for &site in sites {
        if site > prev && site <= sequence.len() {
            fragments.push(sequence[prev..site].to_string());
            prev = site;
        }
    }

    // Last fragment
    if prev < sequence.len() {
        fragments.push(sequence[prev..].to_string());
    }

    fragments
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trypsin_basic_digestion() {
        // PEPTIDEK|ANOTHERPEPTIDER|LASTPART
        // Trypsin cuts after K and R (not before P)
        let peptides = digest(
            "PEPTIDEKANOTHERPEPTIDERLASTPART",
            "P001",
            &Enzyme::Trypsin,
            0,
        );
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        assert!(seqs.contains(&"PEPTIDEK"));
        assert!(seqs.contains(&"ANOTHERPEPTIDER"));
    }

    #[test]
    fn trypsin_does_not_cut_before_p() {
        // KP should NOT be a cleavage site for Trypsin
        let peptides = digest("AVCDEFKPGHIKLMNR", "P001", &Enzyme::Trypsin, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // "AVCDEFKPGHIK" should be one peptide (K followed by P → no cut)
        assert!(seqs.contains(&"AVCDEFKPGHIK"));
    }

    #[test]
    fn trypsinp_cuts_before_p() {
        // TrypsinP cuts after K/R even before P
        // Sequence: AVCDEFK | PSTGHIKLMNQR (TrypsinP cuts at K pos7, then K pos14, R pos18)
        let peptides = digest("AVCDEFKPSTGHIKLMNQR", "P001", &Enzyme::TrypsinP, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        assert!(
            seqs.contains(&"AVCDEFK"),
            "expected AVCDEFK, got: {:?}",
            seqs
        );
        assert!(
            seqs.contains(&"PSTGHIK"),
            "expected PSTGHIK, got: {:?}",
            seqs
        );
    }

    #[test]
    fn lysc_cuts_after_k_only() {
        let peptides = digest("PEPTIDEKANOTHERRPART", "P001", &Enzyme::LysC, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        assert!(seqs.contains(&"PEPTIDEK"));
        // R should not be a cleavage site for LysC
        assert!(seqs.contains(&"ANOTHERRPART"));
    }

    #[test]
    fn gluc_cuts_after_de() {
        let peptides = digest("AVCSQEDFGHIKLMNE", "P001", &Enzyme::GluC, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // Should cut after D and E
        assert!(seqs.iter().any(|s| s.ends_with('D') || s.ends_with('E')));
    }

    #[test]
    fn aspn_cuts_before_d() {
        let peptides = digest("AVCSEFGDKLMNPQRST", "P001", &Enzyme::AspN, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // Should cut BEFORE D → "AVCSEFG" and "DKLMNPQRST"
        assert!(seqs.contains(&"AVCSEFG"));
        assert!(seqs.contains(&"DKLMNPQRST"));
    }

    #[test]
    fn chymotrypsin_cuts_after_fwyl() {
        let peptides = digest("AVCDEFGHIKLMNPQRSTW", "P001", &Enzyme::Chymotrypsin, 0);
        let seqs: Vec<&str> = peptides.iter().map(|p| p.sequence.as_str()).collect();
        // Should cut after F
        assert!(seqs.iter().any(|s| s.ends_with('F')));
    }

    #[test]
    fn missed_cleavages_produce_longer_peptides() {
        let mc0 = digest("PEPTIDEKANOTHERRLASTR", "P001", &Enzyme::Trypsin, 0);
        let mc1 = digest("PEPTIDEKANOTHERRLASTR", "P001", &Enzyme::Trypsin, 1);
        // With missed cleavages, should have more peptides (including merged ones)
        assert!(mc1.len() >= mc0.len());
    }

    #[test]
    fn peptide_mass_calculation() {
        // Glycine: 57.021464 + water (18.010565)
        let mass = peptide_mass("GGGGGG");
        let expected = 57.021464 * 6.0 + WATER_MASS;
        assert!((mass - expected).abs() < 0.001);
    }

    #[test]
    fn peptide_mz_calculation() {
        let mass = 1000.0;
        let mz_z2 = peptide_mz(mass, 2);
        // (1000 + 2*1.007276) / 2 = 501.007276
        assert!((mz_z2 - 501.007276).abs() < 0.001);
    }

    #[test]
    fn peptide_length_filter() {
        // Very short peptides (< 6 aa) should be filtered out
        let peptides = digest("AVKCDKEFGHIKLMNR", "P001", &Enzyme::Trypsin, 0);
        for p in &peptides {
            assert!(p.sequence.len() >= 6, "peptide too short: {}", p.sequence);
        }
    }
}
